# Generated by Django 4.2.1 on 2023-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='discout_price',
            field=models.FloatField(default=0),
        ),
    ]
