# Generated by Django 4.2.1 on 2023-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_description_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='discout_price',
            field=models.FloatField(default=0),
        ),
    ]
